language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO="Django>=1.11.0,<2.0.0"
  - DJANGO="Django>=2.0.0,<2.1.0"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.0.0,<2.1.0"

install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run runtests.py

after_success:
  - coveralls
